### ISSUE TITLE
Transcriber's transcribe method fails to transcribe duplicate words.

### ISSUE THREAD

**Issue by G-Thor** [grammatek/ice-g2p#4] opened 2022-02-09 12:59 UTC
The Transcriber object's transcribe method converts the tokenized input sentence to a dict before transcribing it. This has the unfortunate effect that each unique word only gets transcribed once per sentence. 
So if a sentence contains duplicate words (which is quite common, especially for conjunctions and prepositions), all but the first instance of them are skipped during transcription.
To reproduce this you can simply apply the transcribe method on e.g. the sentence "það þarf að fara að laga þetta", and you should see that the second "að" will not be represented in the output.

**Comment by bnika** [comment] 2022-02-09 13:12
I can't reproduce this error, can you give me an example?

**Comment by G-Thor** [comment] 2022-02-09 13:30
Sorry, this only occurs when syllabification is performed as well, since the dict is used only for syllabified transcription.

so an example using the command line would be
`python ./src/ice_g2p/main.py -i "það þarf að fara að laga þetta" -y`
The output is "T a:1 D. T a1 r v. a:1 D. f a:1. r a0. l a:1. G a0. T E1 h. t a0 "
but should be "T a:1 D. T a1 r v. a:1 D. f a:1. r a0. **a:1 D.** l a:1. G a0. T E1 h. t a0 "

**Comment by bnika** [comment] 2022-02-09 14:18
Thanks, should be fixed now

**Closed as completed** 2022-02-09 15:10 UTC
